apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ciutOv8jgLlETZnGqY74O9t6,iv:j+cK+F/cYHkeTrCK//ttsDL9VIAgy45aUzb980EBV/k=,tag:ThQKherb2KeGhohJV8zOOA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:SVe66FYsztVYwJXMlQzElrnEOwDdz22qnNZbwpSfPtEPsoorOw==,iv:LYnKlnV4/ZU2qjgTDcSjH0jGM3I0wcQ+WB8uu2L4EOI=,tag:mUrrUtL/1soT/o/QiRfPnA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:cLjh/jatClqoDd8y,iv:ydTMkZP7lN0RUAEE1dg8yN5/5dhwJpe2s7AVIHPfBj8=,tag:iLUp2xS6bkjUJ7lRNMyTgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vdyvfg2cwndwrvdvcq7elk0875cvhnjajpswmtqyz8g8ejn8egxqevzwme
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbXdjRUVyUDRKVG1jYkpO
            OUxseGtXdFFWeEp1UVllRlRhbUFoUENqY1NrCnpwZnE0bGFGRTRaNjZPZ2M2TnFw
            V2dWNDFoZGpRU1BlUm5PaEk0QStZZ2cKLS0tIFJuQkxseFpiRktvL1VDd2dPKzNS
            eHBMQllZYlBrMjVTU2d0Qmg0Mmp1dUEK9v7JHO8jZfrbDEy4vAOAf1Bt81KmbC4m
            gHs8lCIUd8LSnc/o1yn42yheM9XgDmHwI4LLRVhvpXgrZlqlmCKsXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T02:44:55Z"
    mac: ENC[AES256_GCM,data:yUgoGCY9PPW9SRrt9kPjxdf0dBcoMLtu1DNYHiopK3xLTAZAna5iHXGShe932cIxfh/6FKw0/JCO7XuISOo3r/uouDzpMm/jg5YI01RHyP4PZ0H9btcb+QEXkTRkWJBt7tQqieraVJlCdu70dOfYIz2URmPuEpdHsPWUtr6ARCE=,iv:nci1mQtOcnfqd1JHArqBsk7KE7Q8Kn/B7lwUuoCYkPI=,tag:PbiTnJyBuliA9l1FO/LgDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
