---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1vdyvfg2cwndwrvdvcq7elk0875cvhnjajpswmtqyz8g8ejn8egxqevzwme
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1vdyvfg2cwndwrvdvcq7elk0875cvhnjajpswmtqyz8g8ejn8egxqevzwme
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1vdyvfg2cwndwrvdvcq7elk0875cvhnjajpswmtqyz8g8ejn8egxqevzwme
