apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:whcSyph8Un76oFbMHbntdJUGznDy8Os2tsFb1y25lwQa4/YnckvCGw==,iv:0VWW2zkvgYzUbNC60RFnrqWTxoGEA8zhgw0rUlvw/GE=,tag:FTtROeEQr1sFMcvUHiMRpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vdyvfg2cwndwrvdvcq7elk0875cvhnjajpswmtqyz8g8ejn8egxqevzwme
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOWozVnJTQkt6RWZFUzVD
            eCtxOHhoNGdiOXZ1SFllSEIyLy9RYW9KeTNFClY1QjhGcnFrU1pNQjVmUU5lTDRI
            dE91RHNwTFk1UnJYdElETUJDQlQxUnMKLS0tIHp2amQ0a2ZiSXpHWEJoTWE5eTN1
            NDZZZ1JkWGlWS2RZb0pvUmM4enR0RzQKW+ImYG1wCYt0Dl7w1zV12qzctcOf9BdG
            UNU6rSW4awX+pY/AnSfUXE+VDTuXTG5T4Ma7Xv6QHjTlIF0A3Rt0nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T02:44:55Z"
    mac: ENC[AES256_GCM,data:uG87bv6kFA/rUH1BODH7AhdSHQhWFIxBO1G0aTbm5qWrEyVrbH8uaa06TNBqKTz+I5yL8JRkKKg5TdHvM39mwBT2A2DbfvkYdqzSkOTZ+fUc1vBM6D988XxXN6EBW99R2WplMLdnyZR30mmX+MXWk1fUTNIdEgvy/TRadTtKP14=,iv:C1IfTPS/JReL9hZVV1+rGFIVKuC+Kn2/HUQnVB1zdS8=,tag:KC7fnGg3vvmYi++rF05yeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
