apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:LByRnCLo/UOMQsQwDQt8o6Cf,iv:UDnul4x9rYc5BsytylBgIQTNWxCy+m+W+TVuqjGGLNE=,tag:5oRFx7++EI75tkfeF3ibWg==,type:str]
    api-key: ENC[AES256_GCM,data:AtQoEERqplgxQy1wTIn9i4RRukvKNmO18KhgxBWLRxnvquwuXg==,iv:7Vr6X6688XejUiQFvhseWx6es/qn185R+k+QuL0xIUU=,tag:AUT8z2Fqfz1G2CclfKwZ+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vdyvfg2cwndwrvdvcq7elk0875cvhnjajpswmtqyz8g8ejn8egxqevzwme
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSXc3UzVJL1dzZE9KbGhI
            ZnB2YysrQ2JkNWcwbHRZbHBPTUhyK2k1QzFrClBBQ0xSQkU1T1JYSUtENEZPMGVR
            ei9Ld1dQMURNeXBTN3Fta2pJUWw1cnMKLS0tIHpXZk1oN1BST25xeEpxY0tjbkZ4
            dksrdlJ5M2RzQnVXVVV6dGxzZWJCaEEKQlx7mhwkRkGfZ/jxFAQecFX098HC+6yY
            qslDhZNMelb1vsLsYGRl2z9S/RHliv3OPvq0XtKngjlRu29MtcTw+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T02:44:55Z"
    mac: ENC[AES256_GCM,data:6LF9beQZ0dFp6E49yW0XlOvJ8Uk26Z165Hrf7LBVgfW2oRxQ37V9RFGxHI9qLDlu4Hmy7CK2AiZU8tMg+XnFw7uEn1ciLIc84HLmKBhIYZIzuRXyCU5WneeAyWJWs7jPoRLxCxg/wRbs22RPau37v0l8Xb7suDo0vJt3sQTyCG8=,iv:D6lnc46D0rAg/HAH+u7dIJSWbFwDs+5f3ClOqv/XMyU=,tag:XDkiNDSY1dLv0MFj9X2Qog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
